name: CI Java Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout develop branch 
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Clean previous Maven build
      run: mvn clean -B
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Show target folder contents
      run: ls target/ -a

    - name: Upload JAR artifact to Github Actions
      uses: actions/upload-artifact@v4.4.3
      with:
        name: building-info
        path: target/*.jar
